site_name: GROBID-Dictionaries Documentation
repo_url: https://github.com/MedKhem/grobid-dictionaries/
repo_name: GitHub
theme: readthedocs
site_description: Documentation for GROBID-Dictionaries
docs_dir: docs
include_search: true
pages:
- ['index.md', 'Home']
- ['Install.md', 'About']
- ['Training.md', 'Training']
- ['Generation_training_data.md', 'Generation of training data']
- ['Service_mode.md', 'Service mode']
- ['Docker.md', 'Docker']
